[global]
hash = "xxh3_128"
sync_strategy = ["reflink"]

[import]
store_exif = false
rename_template = "$filename.$n.$ext"
path_template = "$year/$mon-$day/$device/$filename"
allowed_extensions = [
    "jpg",
    "jpeg",
    "heic",
    "heif",
    "dng",
    "cr2",
    "cr3",
    "nef",
    "nrw",
    "arw",
    "raf",
    "orf",
    "rw2",
    "pef",
    "raw",
    "mov",
    "mp4",
]
