//! Scratch test: verify the exif crate can read EXIF fields from
//! synthetic JPEGs generated by tests/gen_fixtures.py.
//!
//! Run: cargo test -p svault-core --test scratch_exif -- --nocapture

use std::{fs::File, io::BufReader, path::Path};

const FIXTURE_DIR: &str = concat!(env!("CARGO_MANIFEST_DIR"), "/../tests/fixtures/source");

#[test]
fn exif_date_device_from_apple_jpeg() {
    let path = Path::new(FIXTURE_DIR).join("apple_with_exif.jpg");
    let file = File::open(&path).expect("fixture not found — run gen_fixtures.py first");
    let mut reader = BufReader::new(file);

    match exif::Reader::new().read_from_container(&mut reader) {
        Ok(exif_data) => {
            let dt = exif_data
                .get_field(exif::Tag::DateTimeOriginal, exif::In::PRIMARY)
                .map(|f| format!("{}", f.display_value()));
            let make = exif_data
                .get_field(exif::Tag::Make, exif::In::PRIMARY)
                .map(|f| format!("{}", f.display_value()));
            let model = exif_data
                .get_field(exif::Tag::Model, exif::In::PRIMARY)
                .map(|f| format!("{}", f.display_value()));

            println!("DateTimeOriginal : {:?}", dt);
            println!("Make             : {:?}", make);
            println!("Model            : {:?}", model);

            // If these fail, the exif crate cannot parse Pillow+piexif JPEGs.
            // That explains why import always falls back to mtime/Unknown.
            assert!(dt.is_some(), "exif crate did not find DateTimeOriginal");
            assert!(make.is_some(), "exif crate did not find Make");
        }
        Err(e) => {
            println!("exif read error: {e}");
            panic!("exif crate failed to parse synthetic JPEG: {e}");
        }
    }
}

#[test]
fn exif_no_exif_jpeg() {
    let path = Path::new(FIXTURE_DIR).join("no_exif.jpg");
    let file = File::open(&path).expect("fixture not found");
    let mut reader = BufReader::new(file);

    // Expect either an error or empty fields — no panic
    match exif::Reader::new().read_from_container(&mut reader) {
        Ok(exif_data) => {
            let dt = exif_data
                .get_field(exif::Tag::DateTimeOriginal, exif::In::PRIMARY);
            println!("DateTimeOriginal (should be None): {:?}",
                dt.map(|f| format!("{}", f.display_value())));
            assert!(dt.is_none(), "no_exif.jpg should have no DateTimeOriginal");
        }
        Err(e) => println!("no_exif.jpg: exif parse error (expected): {e}"),
    }
}
